name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Run tests
      run: sbt test
    
    - name: Test and make coverage report
      run: |
        sbt clean coverage test
        sbt coverageReport
        
    - name: SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sbt -Dsonar.login=$SONAR_TOKEN sonarScan
      
    - name: Assembly
      run: sbt "clean; set test in assembly := {}; assembly"

    - name: Deploy to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: target/scala-2.13/bloate4-assembly-0.1.jar
        remote: /home/bloate4/builds/bloate4-assembly-0.1.jar
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
