name: release
on:
  release:
    types: [published, created, edited]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Release
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER2 }}
        password: ${{ secrets.SSH_PASSWORD2 }}
        
        script: |
          cp /home/bloate4/builds/bloate4-assembly-0.1.jar /home/bloate4/
          systemctl status bloate4.service
          
